### ISSUE TITLE
0.15.0-dev+73b131a Fails to show builds and can't install wings of dawn

### ISSUE THREAD

**Issue by Levi--G** [ngld/knossos#47]
Trying to install WOD, but i receive an error: (...) mod "fso-wod" wasn't found!

Additionally i can't see the Builds version in the list.

These are the logs:
``` log
INFO:MainThread:launcher.main: Running Knossos 0.15.0-dev+73b131a on PyQt5 and Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)].
INFO:MainThread:launcher.main: OpenSSL version: OpenSSL 1.1.1q  5 Jul 2022
INFO:MainThread:util.call: Running ['L:\\Games\\Knossos\\7z.exe', '-h']
INFO:MainThread:integration.init: Activating Windows integration...
INFO:MainThread:windows.watch_task: Starting task LoadLocalModsTask (active tasks: 1)
INFO:MainThread:windows.watch_task: Starting task FetchTask (active tasks: 2)
INFO:Thread-8:progress._deinit: Setting LoadLocalModsTask as finished after 0.023225 seconds
INFO:Thread-9:progress._next_step: Entering step 1 of 2 in task FetchTask.
INFO:Thread-1:util.download: Downloading "https://cf.fsnebula.org/storage/repo.json"...
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20180725 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20201218 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20180924 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20181111 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20181113 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20181114 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20181218 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200614 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200613 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20191223 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20191228 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20200107 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20200114 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20200119 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 3.8.1-20200129 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200206 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200209 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200412 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20200420 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20201116 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20201222 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 20.1.0-20210122 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 21.3.0-20210508 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 21.5.0-20211101 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 21.5.0-20220216 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 21.5.0-20220318 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "FSO" 22.3.0-20221115 (FSO)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "Wings of Dawn Builds" 17.0.0 (fso-wod)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "Wings of Dawn Builds" 17.0.1 (fso-wod)> is empty, ignoring it!
WARNING:Thread-1:repo.add_mod: Mod <Mod "WarMade Builds" 922.2.0 (WM-FSO)> is empty, ignoring it!
INFO:Thread-1:progress._next_step: Entering step 2 of 2 in task FetchTask.
INFO:Thread-1:progress._next_step: Task FetchTask completed all steps after 12.390874 seconds.
INFO:Thread-1:progress._deinit: Setting FetchTask as finished after 12.391281 seconds
ERROR:MainThread:windows.show_packages: Well, I won't be installing that...
Traceback (most recent call last):
  File "knossos\windows.py", line 681, in show_packages
  File "knossos\repo.py", line 337, in process_pkg_selection
  File "knossos\repo.py", line 744, in resolve_deps
  File "knossos\repo.py", line 217, in query
knossos.repo.ModNotFound: Mod "fso-wod" wasn't found!
ERROR:MainThread:windows.show_packages: Well, I won't be installing that...
Traceback (most recent call last):
  File "knossos\windows.py", line 681, in show_packages
  File "knossos\repo.py", line 337, in process_pkg_selection
  File "knossos\repo.py", line 744, in resolve_deps
  File "knossos\repo.py", line 217, in query
knossos.repo.ModNotFound: Mod "fso-wod" wasn't found!

```

**Comment by schielchen** [comment]
Just tries to install it from within Knossos, but that does not seem the right thing to do (so I wonder why it is there).
https://www.hard-light.net/forums/index.php?topic=93740.0  might help you
